TOPIC_KEYWORDS = {
    "llm_eval": [
        "evaluation",
        "benchmark",
        "judge model",
        "hallucination",
        "factuality",
        "rag evaluation",
        "retrieval evaluation",
        "robustness",
        "red teaming",
        "safety eval",
        "alignment eval",
        "automated eval",
    ],
    "ai_safety": [
        "ai safety",
        "alignment",
        "harmlessness",
        "oversight",
        "constitutional ai",
        "red teaming",
        "misuse",
        "deception",
        "control",
        "model safety",
        "risk",
        "governance",
    ],
    "agents": [
        "agent",
        "agents",
        "agentic",
        "tool use",
        "tool-use",
        "planning",
        "reasoning loop",
        "multi-agent",
        "autonomous workflow",
        "task execution",
        "web agent",
    ],
}